unbind r
bind r source-file ~/.tmux.conf

# C-s prefix for better ergonomic
set -g prefix C-s

# vim-style navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g mode-keys vi
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

set -g pane-border-style fg=colour242
set -g pane-active-border-style fg=#A6C0D0
set -g status-right-length 250
set -g status-left-length 250
set -g status-interval 1

set-option -g status-position top

# pane splits and new windows should open to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

#+--------+
#+ Status +
#+--------+
#+--- Colors ---+
set -g @bars-default "#7aa2f7"
set -g @background "#1a1b26"
set -g @dark-text "#1a1b26"
set -g @light-text "#c0caf5"
set -g @active-window-bg "#bb9af7"
set -g @window-bg "#414868"

#+--- Bars ---+
set -g status-left "#[fg=#{@dark-text},bg=#{@bars-default},bold] #S #[fg=#{@bars-default},bg=#{@background},nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=#{@window-bg},bg=#{@background},nobold,noitalics,nounderscore]#[fg=#{@light-text},bg=#{@window-bg}] %Y-%m-%d #[fg=#{@light-text},bg=#{@window-bg},nobold,noitalics,nounderscore]#[fg=#{@light-text},bg=#{@window-bg}] %H:%M:%S #[fg=#{@bars-default},bg=#{@window-bg},nobold,noitalics,nounderscore]#[fg=#{@dark-text},bg=#{@bars-default},bold] #H "

#+--- Windows ---+
set -g window-status-format "#[fg=#{@background},bg=#{@window-bg},nobold,noitalics,nounderscore] #[fg=#{@light-text},bg=#{@window-bg}]#I #[fg=#{@light-text},bg=#{@window-bg},nobold,noitalics,nounderscore] #[fg=#{@light-text},bg=#{@window-bg}]#W #F #[fg=#{@window-bg},bg=#{@background},nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=#{@background},bg=#{@active-window-bg},nobold,noitalics,nounderscore] #[fg=#{@dark-text},bg=#{@active-window-bg}]#I #[fg=#{@dark-text},bg=#{@active-window-bg},nobold,noitalics,nounderscore] #[fg=#{@dark-text},bg=#{@active-window-bg}]#W #F #[fg=#{@active-window-bg},bg=#{@background},nobold,noitalics,nounderscore]"
set -g window-status-separator ""

set -g status-style bg=default

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
