#+--------+
#+ Status +
#+--------+

#+--- Colors ---+
set -g @bars-default "#61afef"
set -g @background "#fafafa"
set -g @dark-text "#fafafa"
set -g @light-text "#383a42"
set -g @active-window-bg "#a626a4"
set -g @window-bg "#d0d0d0"

set -g pane-border-style fg="#3e4452"
set -g pane-active-border-style fg="#61afef"

set -g message-style fg="#abb2bf",bg="#3e4452"
set -g mode-style fg="#282c34",bg="#e5c07b"

set -g status-style bg="#282c34"
